INSERT INTO forma_contratacao (id, descricao) VALUES (nextval('forma_contratacao_id_seq'), 'Carteira Assinada (CLT)');
INSERT INTO forma_contratacao (id, descricao) VALUES (nextval('forma_contratacao_id_seq'), 'Trabalho com contrato PJ (freelancer)');
INSERT INTO forma_contratacao (id, descricao) VALUES (nextval('forma_contratacao_id_seq'), 'Contratação temporária');
INSERT INTO forma_contratacao (id, descricao) VALUES (nextval('forma_contratacao_id_seq'), 'Trabalho parcial');
INSERT INTO forma_contratacao (id, descricao) VALUES (nextval('forma_contratacao_id_seq'), 'Estágio');
INSERT INTO forma_contratacao (id, descricao) VALUES (nextval('forma_contratacao_id_seq'), 'Jovem Aprendiz');
INSERT INTO forma_contratacao (id, descricao) VALUES (nextval('forma_contratacao_id_seq'), 'Terceirização');
INSERT INTO forma_contratacao (id, descricao) VALUES (nextval('forma_contratacao_id_seq'), 'Home Office ou trabalho remoto');
INSERT INTO forma_contratacao (id, descricao) VALUES (nextval('forma_contratacao_id_seq'), 'Trabalho Intermitente');
INSERT INTO forma_contratacao (id, descricao) VALUES (nextval('forma_contratacao_id_seq'), 'Trabalho Autônomo');